/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author Akash Bahri
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    public String ErrorMessage="Uncaught Error";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        FNameLabel = new javax.swing.JLabel();
        FNameText = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        AgeText = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        LNameLabel = new javax.swing.JLabel();
        LNameText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        MessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(56, 136, 117));

        TitleLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("User Form ");

        FNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FNameLabel.setText("First Name");

        FNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTextActionPerformed(evt);
            }
        });
        FNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FNameTextKeyPressed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AgeLabel.setText("Age");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email");

        SubmitButton.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        LNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LNameLabel.setText("Last Name");

        EmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextActionPerformed(evt);
            }
        });

        MessageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MessageLabel.setText("Message");

        MessageTextArea.setColumns(20);
        MessageTextArea.setRows(5);
        jScrollPane1.setViewportView(MessageTextArea);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeLabel)
                            .addComponent(EmailLabel)
                            .addComponent(FNameLabel)
                            .addComponent(LNameLabel)
                            .addComponent(MessageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(AgeText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FNameText, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(203, 203, 203))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameLabel)
                    .addComponent(FNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameLabel)
                    .addComponent(LNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessageLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        
        String FName=FNameText.getText();
        String LName=LNameText.getText();
        String Email=EmailText.getText();
        String Age= AgeText.getText();
        String Message=MessageTextArea.getText();

        String Output = "No Input";
        Output="First Name: "+FName+"\nLast Name: "+LName+"\nEmail: "+Email+"\nAge: "+Age+"\nMessage: "+Message;
        


        String Numbers = "[0-9]+";
        Pattern NumberRegex =Pattern.compile(Numbers);
        Matcher MAge =NumberRegex.matcher(Age);

        String NameRegex = "[a-zA-Z]+";
        Pattern NamePattern =Pattern.compile(NameRegex);
        Matcher MatchFname =NamePattern.matcher(FName);
        Matcher MatchLname =NamePattern.matcher(LName);

        try{
              if(MatchFname.matches()==false){
                
                throw new Exception("First Name is not a string");
            }

            if(MatchLname.matches()==false){
                
                throw new Exception("Last Name is not a string");
            }
            if(FName.isEmpty()){
                
                throw new Exception("First Name is empty");
            }
            if(LName.isEmpty()){
                
                throw new Exception("Last Name is empty");
            }

            if(MAge.matches()==false){
                
                throw new Exception("Age is not a number");
            }
            if(Integer.parseInt(Age)<18){
                
                throw new Exception("Age is less than 18");
            }
            if(Age.isEmpty()){
                
                throw new Exception("Age is empty");
            }          

            if(Email.contains("@")==false){
                
                throw new Exception("Email does not contain @");
            }

            if(Email.contains(".")==false){
                
                throw new Exception("Email does not contain .");
            }

            if(Email.contains(" ")){

                throw new Exception("Email contains space");
            }

            if(Email.isEmpty()){
                
                throw new Exception("Email is empty");
            }

            if(Message.isEmpty()){
                
                throw new Exception("Message is empty");
            }

         JOptionPane.showMessageDialog(this,Output, "User Information", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(this,e.getMessage(), "User Information", JOptionPane.ERROR_MESSAGE);
        }
        
       
        
        
        
        
        
        System.out.println(FName+Age);
        
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void EmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextActionPerformed

    private void FNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FNameTextActionPerformed

    private void FNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FNameTextKeyPressed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeText;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel FNameLabel;
    private javax.swing.JTextField FNameText;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel LNameLabel;
    private javax.swing.JTextField LNameText;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextArea MessageTextArea;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
